[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.23"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 100

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[profile.coverage]
ignored_paths = ["script"]
coverage_exclude = ["script/*"]

[rpc_endpoints]
local = "http://localhost:8545"
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
monad_testnet = "${MONAD_TESTNET_RPC_URL}"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true 